services:
  postgres:
    image: postgres:latest
    container_name: trivago-test-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: trivago-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - trivago-test-postgres-data:/data/postgres

  app:
    container_name: trivago-test-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres

volumes:
  trivago-test-postgres-data: